import type { Metadata } from "next";
import { LegalItem, LegalList, LegalPage, type LegalSection } from "../_components/LegalPage";

export const metadata: Metadata = {
  title: { absolute: "Terms and Conditions | Tasking" },
  description: "Terms governing access to and use of the Tasking collaboration platform.",
  alternates: { canonical: "/landing-page/terms" },
  openGraph: { title: "Terms and Conditions | Tasking", description: "Terms governing access to and use of the Tasking collaboration platform.", url: "/landing-page/terms", type: "website" },
  twitter: { card: "summary", title: "Terms and Conditions | Tasking", description: "Terms governing access to and use of the Tasking collaboration platform." },
};

const sections: LegalSection[] = [
  { id: "agreement", title: "Agreement to these terms", content: <><p>These Terms and Conditions form an agreement between you and Pixpel SL (&quot;Tasking&quot;, &quot;we&quot;, &quot;us&quot;). By creating an account, joining a workspace, or using Tasking, you agree to these terms and our Privacy Policy.</p><p>If you use Tasking for an organization, you confirm that you are authorized to accept these terms on its behalf. If you do not agree, do not use the service.</p></> },
  { id: "accounts", title: "Accounts and eligibility", content: <LegalList><LegalItem>You must provide accurate information and keep it current.</LegalItem><LegalItem>You are responsible for activity under your account and for keeping credentials secure.</LegalItem><LegalItem>You must be legally able to enter this agreement. Minors may use Tasking only with required consent and organizational authorization.</LegalItem><LegalItem>Notify Tasking promptly if you suspect unauthorized access.</LegalItem></LegalList> },
  { id: "workspaces", title: "Workspaces and administration", content: <><p>Workspace owners and administrators control membership, roles, projects, channels, content access, and certain retention decisions. Your organization is responsible for its workspace instructions and for obtaining any required permissions from members.</p><p>If you join an organization-managed workspace, its administrators may access, manage, export, restrict, or delete workspace content and may remove your access.</p></> },
  { id: "acceptable-use", title: "Acceptable use", content: <><p>You may not use Tasking to break the law, violate others&apos; rights, distribute malware, harass people, send spam, bypass access controls, probe security without permission, overload infrastructure, scrape the service, or resell access unless authorized.</p><p>You may not upload content you do not have the right to use or attempt to access another user&apos;s account, workspace, mail connection, files, or confidential information.</p></> },
  { id: "content", title: "Your content", content: <><p>You retain ownership of content you submit. You grant Tasking a limited license to host, process, transmit, display, back up, and otherwise handle that content only as needed to operate, secure, and improve the service and satisfy your instructions.</p><p>You are responsible for your content, its legality, and the permissions required to share it. We may remove or restrict content that violates these terms or creates security or legal risk.</p></> },
  { id: "ai-mail", title: "AI and connected mail", content: <><p>Cleotilda output may be incomplete or incorrect. You remain responsible for reviewing AI-created tasks, summaries, recommendations, messages, and other actions before relying on them.</p><p>When connecting an email account, you confirm that you are authorized to access it and permit Tasking to use the supplied connection solely to perform mail operations you request. You remain responsible for provider terms, recipients, and sent content.</p></> },
  { id: "plans", title: "Plans, billing, and changes", content: <><p>Features, limits, and pricing may vary by plan. Paid subscriptions renew according to the ordering terms shown at purchase unless cancelled. Taxes may apply. Except where law requires otherwise, fees already paid are non-refundable.</p><p>We may change features or pricing with reasonable notice. Material reductions to a paid plan will be handled according to applicable ordering terms.</p></> },
  { id: "availability", title: "Service availability", content: <><p>We work to keep Tasking reliable and secure, but the service is provided on an &quot;as available&quot; basis. Maintenance, third-party failures, internet conditions, security events, or emergencies may interrupt access.</p><p>Beta and preview features may change or be discontinued and should not be used as the sole basis for critical operations.</p></> },
  { id: "termination", title: "Suspension and termination", content: <><p>You may stop using Tasking at any time. We may suspend or terminate access for material breach, security risk, unlawful use, non-payment, or where required by law. When practical, we will provide notice and an opportunity to resolve the issue.</p><p>Provisions concerning ownership, payment, disclaimers, liability, and dispute handling survive termination where applicable.</p></> },
  { id: "liability", title: "Disclaimers and liability", content: <><p>To the maximum extent permitted by law, Tasking is provided without implied warranties of merchantability, fitness for a particular purpose, or non-infringement. We do not guarantee uninterrupted operation or the accuracy of AI output.</p><p>To the maximum extent permitted by law, neither party is liable for indirect, incidental, special, consequential, or punitive damages. Tasking&apos;s aggregate liability will not exceed the amount paid for the service during the twelve months before the event giving rise to the claim. Mandatory legal rights remain unaffected.</p></> },
  { id: "general", title: "General terms and contact", content: <><p>These terms and referenced policies are the entire agreement for the service unless a separate written agreement applies. If one provision is unenforceable, the remainder continues. Failure to enforce a provision is not a waiver.</p><p>We may update these terms with reasonable notice for material changes. Continued use after the effective date means you accept the revised terms. Questions may be directed to Tasking support through the contact channel published at taskinglife.io.</p></> },
];

export default function TermsPage() {
  return <LegalPage eyebrow="Legal · Terms" title="Terms built for clear collaboration." summary="These terms explain the rules, responsibilities, and protections that apply when you use Tasking." updated="August 4, 2026" sections={sections} />;
}
