import type { Metadata } from "next";
import { LegalItem, LegalList, LegalPage, type LegalSection } from "../_components/LegalPage";

export const metadata: Metadata = {
  title: { absolute: "Privacy Policy | Tasking" },
  description: "Learn how Tasking collects, uses, protects, and manages personal information.",
  alternates: { canonical: "/landing-page/privacy" },
  openGraph: { title: "Privacy Policy | Tasking", description: "Learn how Tasking collects, uses, protects, and manages personal information.", url: "/landing-page/privacy", type: "website" },
  twitter: { card: "summary", title: "Privacy Policy | Tasking", description: "Learn how Tasking collects, uses, protects, and manages personal information." },
};

const sections: LegalSection[] = [
  { id: "scope", title: "Scope", content: <><p>This Privacy Policy explains how Pixpel SL (&quot;Tasking&quot;, &quot;we&quot;, &quot;us&quot;) handles personal information when you use Tasking websites, web and mobile applications, workspaces, collaboration tools, Cleotilda AI, and connected services.</p><p>Your organization may separately control information submitted to its workspace. In that situation, your organization is responsible for its instructions and member access.</p></> },
  { id: "information", title: "Information we collect", content: <LegalList><LegalItem>Account data such as your name, email address, profile image, authentication identifiers, and preferences.</LegalItem><LegalItem>Workspace content such as messages, tasks, comments, files, project details, and activity records.</LegalItem><LegalItem>Connected-service configuration, including encrypted mail credentials when you choose to connect IMAP/SMTP accounts.</LegalItem><LegalItem>Technical data such as browser type, device information, IP address, security events, diagnostics, and feature usage.</LegalItem><LegalItem>Information you provide to support, feedback, surveys, or sales conversations.</LegalItem></LegalList> },
  { id: "use", title: "How we use information", content: <LegalList><LegalItem>Provide, maintain, personalize, and improve Tasking.</LegalItem><LegalItem>Authenticate users, manage workspace permissions, and protect accounts.</LegalItem><LegalItem>Process messages, tasks, files, connected mail, notifications, and AI requests you initiate.</LegalItem><LegalItem>Detect abuse, investigate security incidents, enforce our terms, and comply with law.</LegalItem><LegalItem>Communicate service updates and respond to support requests.</LegalItem></LegalList> },
  { id: "ai", title: "Cleotilda AI", content: <><p>When you use Cleotilda, the content and context required to answer your request may be processed by AI service providers. We limit that processing to delivering the requested feature and apply access controls based on your workspace permissions.</p><p>Do not submit secrets or highly sensitive personal data unless it is necessary and authorized by your organization. AI output may be inaccurate and should be reviewed before important decisions.</p></> },
  { id: "sharing", title: "How information is shared", content: <><p>We do not sell personal information. We may share limited information with infrastructure, hosting, authentication, email, storage, analytics, security, and AI providers that help operate Tasking under contractual safeguards.</p><p>Information may also be shared with workspace members according to permissions, during a business transaction, when you direct us to do so, or when legally required.</p></> },
  { id: "retention", title: "Retention and deletion", content: <><p>We retain information while your account or workspace is active and as reasonably needed to provide the service, meet legal obligations, resolve disputes, and protect security. Retention periods vary by data type and workspace settings.</p><p>Workspace owners may control member access and content retention. Backups may retain deleted information for a limited period before secure expiration.</p></> },
  { id: "security", title: "Security", content: <><p>Tasking uses safeguards including encrypted transport, access controls, row-level authorization, credential encryption, monitoring, and restricted administrative access. No online service can guarantee absolute security.</p><p>You are responsible for protecting your login credentials, using strong authentication, and promptly reporting suspected compromise.</p></> },
  { id: "rights", title: "Your rights and choices", content: <><p>Depending on your location, you may have rights to access, correct, delete, restrict, object to, or export personal information. You can update common profile information within Tasking and may request additional assistance through Tasking support.</p><p>Workspace-controlled content requests may need to be directed to your organization. We may verify your identity before completing a request.</p></> },
  { id: "international", title: "International processing", content: <p>Tasking and its providers may process information in countries other than your own. Where required, we use recognized legal mechanisms and contractual protections for international transfers.</p> },
  { id: "changes", title: "Changes and contact", content: <><p>We may update this policy as Tasking evolves. Material changes will be communicated through the service or website, and the updated date above will change.</p><p>For privacy questions or requests, contact Tasking support through the contact channel published at taskinglife.io and identify the account or workspace involved.</p></> },
];

export default function PrivacyPage() {
  return <LegalPage eyebrow="Legal · Privacy" title="Privacy, explained clearly." summary="This policy describes what information Tasking handles, why we use it, and the choices available to you." updated="August 4, 2026" sections={sections} />;
}
